version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  auth:
    build:
      context: ./backend/auth
    environment:
      - API_PORT=${AUTH_PORT}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    container_name: auth

  profile:
    build:
      context: ./backend/profile
    environment:
      - API_PORT=${PROFILE_PORT}
    ports:
      - ${PROFILE_PORT}:${PROFILE_PORT}
    container_name: profile

  entry:
    build:
      context: ./backend/entry
    environment:
      - API_PORT=${ENTRY_PORT}
    ports:
      - ${ENTRY_PORT}:${ENTRY_PORT}
    container_name: entry

  comp:
    build:
      context: ./backend/comp
    environment:
      - API_PORT=${COMP_PORT}
    ports:
      - ${COMP_PORT}:${COMP_PORT}
    container_name: comp

  frontend:
    build:
      context: ./frontend
    environment:
      - AUTH_PORT=${AUTH_PORT}
      - PROFILE_PORT=${PROFILE_PORT}
      - ENTRY_PORT=${ENTRY_PORT}
      - COMP_PORT=${COMP_PORT}
    ports:
      - 80:80
    container_name: frontend

volumes:
  rabbitmq-data:
  rabbitmq-log:
